name = "il-buco-cleaning"
main = "cloudflare-worker.js"
compatibility_date = "2023-05-18"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "ilbuco-cleaning-db"
database_id = "be8ebe7e-08ff-4db0-b386-21a989302bea"

# R2 Storage binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "ilbuco-clean"

# Environment variables
[vars]
PUBLIC_R2_URL = "https://pub-ACCOUNT_ID.r2.dev/ilbuco-clean"

# Routes
# Uncomment and update with your domain when ready
# [[routes]]
# pattern = "api/*"
# zone_name = "your-domain.com"
